(let [inputs (map #(Double/parseDouble %) (clojure.string/split (read-line) #"\s+"))
      A (nth inputs 0)
      B (nth inputs 1)
      C (nth inputs 2)
      area-triangulo (/ (* A C) 2)
      area-circulo (* 3.14159 (* C C))
      area-trapezio (/ (* (+ A B) C) 2)
      area-quadrado (* B B)
      area-retangulo (* A B)]
  (println (format "TRIANGULO: %.3f" area-triangulo))
  (println (format "CIRCULO: %.3f" area-circulo))
  (println (format "TRAPEZIO: %.3f" area-trapezio))
  (println (format "QUADRADO: %.3f" area-quadrado))
  (println (format "RETANGULO: %.3f" area-retangulo)))