(def vertebralidade (read-line))
(def especie (read-line))
(def alimentacao (read-line))

(cond 
    (and (= vertebralidade "vertebrado") (= especie "ave") (= alimentacao "carnivoro") 
    ) (printf "aguia\n")
    (and (= vertebralidade "vertebrado") (= especie "ave") (= alimentacao "onivoro") 
    ) (printf "pomba\n")
    (and (= vertebralidade "vertebrado") (= especie "mamifero") (= alimentacao "onivoro") 
    ) (printf "homem\n")
    (and (= vertebralidade "vertebrado") (= especie "mamifero") (= alimentacao "herbivoro") 
    ) (printf "vaca\n")
    (and (= vertebralidade "invertebrado") (= especie "inseto") (= alimentacao "hematofago") 
    ) (printf "pulga\n")
    (and (= vertebralidade "invertebrado") (= especie "inseto") (= alimentacao "herbivoro") 
    ) (printf "lagarta\n")
    (and (= vertebralidade "invertebrado") (= especie "anelideo") (= alimentacao "hematofago") 
    ) (printf "sanguessuga\n")
    (and (= vertebralidade "invertebrado") (= especie "anelideo") (= alimentacao "onivoro") 
    ) (printf "minhoca\n")
    )